import Head from "next/head";
import "../node_modules/bootstrap/dist/css/bootstrap.min.css";
import React, { useEffect, useState } from "react";
import Aos from "aos";
import "aos/dist/aos.css";
import Link from "next/link";
import styled, { ThemeProvider } from "styled-components";
import { lightTheme, darkTheme, GlobalStyles } from "./utilities/theme";

const StyledApp = styled.div`
  color: ${(props) => props.theme.fontColor};
`;

const content = [
  {
    title: "Pudfu",
    img: "https://play-lh.googleusercontent.com/8ddL1kuoNUB5vUvgDVjYY3_6HwQcrg1K2fd_R8soD-e2QYj8fT9cfhfh3G0hnSruLKec",
    href: "./components/games/Waterly/Waterly",
  },
  {
    title: "Pudfu",
    img: "https://img.poki.com/cdn-cgi/image/quality=78,width=600,height=600,fit=cover,g=0.5x0.5,f=auto/2c6d5a46cdbceada277c870ce1c389ee.jpg",
    href: "#",
  },
];

export default function Home() {
  const [theme, setTheme] = useState("dark");

  const themeToggler = () => {
    theme === "light" ? setTheme("dark") : setTheme("light");
  };

  useEffect(() => {
    Aos.init();
  }, []);

  return (
    <div className="">
      <Head>
        <title>Haumex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-center mt-1">
        <ThemeProvider theme={theme === "light" ? lightTheme : darkTheme}>
          <GlobalStyles />
          <StyledApp>
            <button
              className="btn btn-secondary"
              onClick={() => themeToggler()}
            >
              Change Theme
            </button>
          </StyledApp>
        </ThemeProvider>
      </div>

      <section className="py-4 py-lg-5 container">
        <div className="row">
          {content.map((item) => (
            <div
              data-aos="fade-zoom-in"
              data-aos-offset="100"
              data-aos-easing="ease-in-sine"
              data-aos-duration="600"
              className="col-11 col-md-6 col-lg-3 mx-0 mb-4"
            >
              <div className="card p-0 overflow-hidden h-100 shadow border border-warning">
                <a href={item.href} className="a-hyperlink">
                  <img src={item.img} className="card-img-top" />
                  <div className="card-body">
                    <h5 className="card-title card-title">{item.title}</h5>
                  </div>
                </a>
              </div>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
