import Head from "next/head";
import "../node_modules/bootstrap/dist/css/bootstrap.min.css";
import React, { useEffect, useState } from "react";
import Aos from "aos";
import "aos/dist/aos.css";
import Link from "next/link";
import styled, { ThemeProvider } from "styled-components";
import { lightTheme, darkTheme, GlobalStyles } from "./utilities/theme";

const StyledApp = styled.div`
  color: ${(props) => props.theme.fontColor};
`;

const content = [
  {
    title: "Waterly",
    img: "https://image.freepik.com/free-vector/many-sharks-cartoon-character-underwater-background_1308-53749.jpg",
    href: "./components/games/Waterly/Waterly",
  },
  {
    title: "Tic Tac Toe",
    img: "https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/01/df/23/01df2352-52ec-2bf8-e0bc-cfe8a3b051ce/source/512x512bb.jpg",
    href: "./components/games/TicTacToe/TicTacToe",
  },
];

export default function Home() {
  const [theme, setTheme] = useState("dark");

  const themeToggler = () => {
    theme === "light" ? setTheme("dark") : setTheme("light");
  };

  useEffect(() => {
    Aos.init();
  }, []);

  return (
    <div className="">
      <Head>
        <title>Haumex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-center mt-1">
        <ThemeProvider theme={theme === "light" ? lightTheme : darkTheme}>
          <GlobalStyles />
          <StyledApp>
            <button
              class="button-82-pushable"
              onClick={() => themeToggler()}
              role="button"
            >
              <span class="button-82-shadow"></span>
              <span class="button-82-edge"></span>
              <span class="button-82-front text">Change Theme</span>
            </button>
          </StyledApp>
        </ThemeProvider>
      </div>

      <section className="py-4 py-lg-5 container">
        <div className="row">
          {content.map((item) => (
            <div
              data-aos="fade-zoom-in"
              data-aos-offset="100"
              data-aos-easing="ease-in-sine"
              data-aos-duration="600"
              className="col-11 col-md-6 col-lg-3 mx-0 mb-4"
            >
              <div className="card p-0 overflow-hidden h-100 shadow">
                <a href={item.href} className="a-hyperlink">
                  <img src={item.img} className="card-img-top" />
                  <div className="card-body">
                    <h5 className="card-title card-title">{item.title}</h5>
                  </div>
                </a>
              </div>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
